[package]
name = "model-lampshade"
version.workspace = true
edition.workspace = true

[lib]
path = "model.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
manifold-rust = "=0.13.1"
earcutr = "=0.4.3"
wasm-bindgen.workspace = true
serde.workspace = true
serde_json.workspace = true

[build-dependencies]
serde_yaml_ng = "=0.10.0"
serde_json.workspace = true
